vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
vim.g.markdown_recommended_style = 0
vim.g.autoformat = true
vim.g.snacks_animate = false
vim.g.lazyvim_picker = "auto"
vim.g.lazyvim_cmp = "auto"
vim.g.ai_cmp = true
vim.g.root_spec = { "lsp", { ".git", "lua" }, "cwd" }
-- Set LSP servers to be ignored when used with `util.root.detectors.lsp`
-- for detecting the LSP root
vim.g.root_lsp_ignore = { "copilot" }
vim.g.deprecation_warnings = false
vim.opt.autowrite = true                                           -- Enable auto write
vim.opt.clipboard = vim.env.SSH_CONNECTION and "" or "unnamedplus" -- Sync with system clipboard
vim.opt.completeopt = "menu,menuone,noselect"
vim.opt.conceallevel = 2                                           -- Hide * markup for bold and italic, but not markers with substitutions
vim.opt.confirm = true                                             -- Confirm to save changes before exiting modified buffer
vim.opt.cursorline = true                                          -- Enable highlighting of the current line
vim.opt.expandtab = true                                           -- Use spaces instead of tabs
vim.opt.fillchars = {
  foldopen = "",
  foldclose = "",
  fold = " ",
  foldsep = " ",
  diff = "╱",
  eob = " ",
}
vim.opt.foldlevel = 99
vim.opt.foldmethod = "indent"
vim.opt.foldtext = ""
vim.opt.formatexpr = "v:lua.LazyVim.format.formatexpr()"
vim.opt.formatoptions = "jcroqlnt" -- tcqj
vim.opt.grepformat = "%f:%l:%c:%m"
vim.opt.grepprg = "rg --vimgrep"
vim.opt.ignorecase = true      -- Ignore case
vim.opt.inccommand = "nosplit" -- preview incremental substitute
vim.opt.jumpoptions = "view"
vim.opt.laststatus = 3         -- global statusline disabled
vim.opt.list = true            -- Show some invisible characters (tabs...
vim.opt.mouse = "a"            -- Enable mouse mode
vim.opt.number = false         -- Print line number
vim.opt.relativenumber = false -- Relative line numbers
vim.opt.pumblend = 10          -- Popup blend
vim.opt.pumheight = 10         -- Maximum number of entries in a popup
vim.opt.ruler = false          -- Disable the default ruler
vim.opt.scrolloff = 10         -- Lines of context
vim.opt.sidescrolloff = 8      -- Columns of context
vim.opt.sessionoptions = { "buffers", "curdir", "tabpages", "winsize", "help", "globals", "skiprtp", "folds" }
vim.opt.shiftround = true      -- Round indent
vim.opt.shiftwidth = 2         -- Size of an indent
vim.opt.shortmess:append({ W = true, I = true, c = true, C = true })
vim.opt.showmode = false
vim.opt.smartcase = true                          -- Don't ignore case with capitals
vim.opt.smartindent = true                        -- Insert indents automatically
vim.opt.spelllang = { "" }
vim.opt.splitbelow = true                         -- Put new windows below current
vim.opt.splitkeep = "screen"
vim.opt.splitright = true                         -- Put new windows right of current
vim.opt.statuscolumn = [[%!v:lua.LazyVim.statuscolumn()]]
vim.opt.tabstop = 2                               -- Number of spaces tabs count for
vim.opt.termguicolors = true                      -- True color support
vim.opt.timeoutlen = vim.g.vscode and 1000 or 300 -- Lower than default (1000) to quickly trigger which-key
vim.opt.undofile = true
vim.opt.undolevels = 10000
vim.opt.virtualedit = "block"          -- Allow cursor to move where there is no text in visual block mode
vim.opt.wildmode = "longest:full,full" -- Command-line completion mode
vim.opt.winminwidth = 5                -- Minimum window width
vim.opt.wrap = false                   -- Disable line wrap
vim.opt.linebreak = true    -- IF wrap is on, break at word boundaries (doesn't enable wrap)
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.signcolumn = "yes"
vim.opt.isfname:append("@-@")
vim.opt.updatetime = 50
vim.opt.laststatus = 0
vim.opt.guicursor = "n:block25,c:ver25,i-ci-ve:ver25,r-cr:hor20,o:hor50"
